### ISSUE TITLE
Working only for Administrator user

### ISSUE THREAD

**Issue by seibei-iguchi** [benjamin-vauchel/CustomUrls#1]
Hi, I can't seem to get this plugin working with any type of user other than the administrator. I select the usergroup as intended but when I create a document as an user from that group, nothing happens - the alias is in the default format. I figured out it must be due to some restrictions on that particular usergroup, since the administrator is the only user with all the permissions. Do you have any idea? Thanks!

**Comment by benjamin-vauchel** [comment]
Thanks for the report. I'll take a look soon.

**Comment by joyceDesignbase** [comment]
Thank you for your super plugin! But I have the same issue, pages that our client saves do not get the custom url, only the admin. Have you been able to take a look at it yet?
Many thanks!

**Comment by benjamin-vauchel** [comment]
I've fixed the bug, but MODx Package Management is down. You still can download the v1.0.0-rc3 tag and install it manually. 
Only the core/components/customurls/model/customurls/customurls.class.php file was updated.

**Comment by benjamin-vauchel** [comment]
Package updated : http://modx.com/extras/package/customurls
